# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f4523afcce0eaa8ffd6ef0a67cc0ad431460cc87b0b45234018fdf75514004680e7d5f21d03fb0f129f2083ff3345088ce307f1f246caf7d50a11fcfcbe129b

test:
  secret_key_base: 3bcd5150775bf4506fe22b2efa627c6c0765ef5f9e5986f03d6c5f607da2bba913f69caabb1067403980e9efa7d52153db763e4bc52e5e28e74d4c9de50595f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
